services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - PORT=3000
      - DB_CONNECTION=postgres
      - TEST=${TEST}
  database:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./asd/asd:/asd:ro
      - /asdf:/asdf
      - type: bind
        source: ./app
        target: /app
        read_only: true
      - type: bind
        source: /1234
        target: /123
        read_only: false
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
